/**
 * Resume export formats: ATS-friendly LaTeX + text-based PDF.
 * TeX is not available on Vercel; PDF is generated with a pure-JS writer
 * (selectable text, single column) so downloads work in serverless.
 */

function escapeLatex(s: string) {
  return s
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

function pdfEscape(s: string) {
  return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapLine(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    const next = cur ? `${cur} ${w}` : w;
    if (next.length > maxChars && cur) {
      lines.push(cur);
      cur = w;
    } else {
      cur = next;
    }
  }
  if (cur) lines.push(cur);
  return lines.length ? lines : [""];
}

function isSectionHeading(trimmed: string) {
  return (
    /^[A-Z][A-Z\s/&-]{2,40}$/.test(trimmed) ||
    /^(professional summary|work experience|experience|education|skills|projects|certifications|ats keywords)/i.test(
      trimmed,
    )
  );
}

export function tailoredResumeToLatex(options: {
  fullName: string;
  company: string;
  title: string;
  resumeText: string;
}): string {
  const { fullName, company, title, resumeText } = options;
  const lines = resumeText.replace(/\r\n/g, "\n").split("\n");

  const body: string[] = [];
  for (const raw of lines) {
    const trimmed = raw.trim();
    if (!trimmed) {
      body.push("");
      continue;
    }
    if (isSectionHeading(trimmed)) {
      body.push(`\\section*{${escapeLatex(trimmed)}}`);
      continue;
    }
    if (/^([•\-\*\u2022]|·|\d+\.)\s+/.test(trimmed)) {
      const content = trimmed.replace(/^([•\-\*\u2022]|·|\d+\.)\s+/, "");
      body.push(`\\item ${escapeLatex(content)}`);
      continue;
    }
    body.push(`${escapeLatex(trimmed)}\\\\`);
  }

  const wrapped: string[] = [];
  let inList = false;
  for (const b of body) {
    if (b.startsWith("\\item ")) {
      if (!inList) {
        wrapped.push("\\begin{itemize}");
        inList = true;
      }
      wrapped.push(b);
    } else {
      if (inList) {
        wrapped.push("\\end{itemize}");
        inList = false;
      }
      wrapped.push(b);
    }
  }
  if (inList) wrapped.push("\\end{itemize}");

  return `% ATS-friendly single-column resume (article class)
% Tailored for: ${title.replace(/%/g, "")} @ ${company.replace(/%/g, "")}
% Generated by Job Hunt Copilot — facts only from source resume
\\documentclass[11pt,letterpaper]{article}
\\usepackage[margin=0.7in]{geometry}
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage{enumitem}
\\usepackage{titlesec}
\\usepackage{hyperref}
\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{0.35em}
\\setlist[itemize]{leftmargin=*,itemsep=0.15em,topsep=0.2em}
\\titleformat{\\section}{\\large\\bfseries\\uppercase}{}{0em}{}[\\titlerule]
\\titlespacing*{\\section}{0pt}{1.1em}{0.45em}

\\begin{document}
{\\LARGE\\bfseries ${escapeLatex(fullName)}}\\\\[0.4em]
{\\small Tailored for ${escapeLatex(title)} at ${escapeLatex(company)}}\\\\[0.8em]

${wrapped.join("\n")}

\\end{document}
`;
}

/**
 * Minimal text PDF writer (PDF 1.4, Helvetica). Selectable text, single column —
 * suitable for ATS upload when DOCX isn't available.
 */
export function tailoredResumeToPdfBytes(options: {
  fullName: string;
  company: string;
  title: string;
  resumeText: string;
}): Uint8Array {
  const pageWidth = 612;
  const pageHeight = 792;
  const margin = 50;
  const fontSize = 10;
  const lineHeight = 13;
  const maxChars = 95;

  const contentLines: string[] = [
    options.fullName,
    `Tailored for ${options.title} at ${options.company}`,
    "",
  ];
  for (const raw of options.resumeText.replace(/\r\n/g, "\n").split("\n")) {
    const t = raw.trimEnd();
    if (!t.trim()) {
      contentLines.push("");
      continue;
    }
    for (const w of wrapLine(t.trim(), maxChars)) contentLines.push(w);
  }

  const linesPerPage = Math.floor((pageHeight - margin * 2) / lineHeight);
  const pages: string[][] = [];
  for (let i = 0; i < contentLines.length; i += linesPerPage) {
    pages.push(contentLines.slice(i, i + linesPerPage));
  }
  if (pages.length === 0) pages.push([options.fullName]);

  const pdfObjects: (string | null)[] = [null];
  const catalogId = 1;
  const pagesId = 2;
  const fontId = 3;
  let nextId = 4;
  const pageIds: number[] = [];
  const streamIds: number[] = [];

  for (let i = 0; i < pages.length; i++) {
    pageIds.push(nextId++);
    streamIds.push(nextId++);
  }

  pdfObjects[catalogId] = `<< /Type /Catalog /Pages ${pagesId} 0 R >>`;
  pdfObjects[pagesId] =
    `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pages.length} >>`;
  pdfObjects[fontId] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";

  for (let i = 0; i < pages.length; i++) {
    const pageLines = pages[i];
    const y = pageHeight - margin;
    const ops: string[] = ["BT", `/F1 ${fontSize} Tf`, `${lineHeight} TL`];
    for (let li = 0; li < pageLines.length; li++) {
      const text = pdfEscape(pageLines[li] || " ");
      if (li === 0) {
        ops.push(`1 0 0 1 ${margin} ${y} Tm`, `(${text}) Tj`);
      } else {
        ops.push("T*", `(${text}) Tj`);
      }
    }
    ops.push("ET");
    const stream = ops.join("\n");
    pdfObjects[streamIds[i]] =
      `<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`;
    pdfObjects[pageIds[i]] =
      `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] ` +
      `/Contents ${streamIds[i]} 0 R /Resources << /Font << /F1 ${fontId} 0 R >> >> >>`;
  }

  let out = "%PDF-1.4\n";
  const offsets: number[] = [0];
  for (let i = 1; i < pdfObjects.length; i++) {
    offsets[i] = Buffer.byteLength(out, "utf8");
    out += `${i} 0 obj\n${pdfObjects[i]}\nendobj\n`;
  }
  const xrefPos = Buffer.byteLength(out, "utf8");
  out += `xref\n0 ${pdfObjects.length}\n`;
  out += "0000000000 65535 f \n";
  for (let i = 1; i < pdfObjects.length; i++) {
    out += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  out += `trailer\n<< /Size ${pdfObjects.length} /Root ${catalogId} 0 R >>\nstartxref\n${xrefPos}\n%%EOF\n`;

  return new Uint8Array(Buffer.from(out, "utf8"));
}

export function resumeExportBaseName(company: string, title: string, fullName: string) {
  const safe = (s: string) => s.replace(/[^a-z0-9]+/gi, "_").replace(/^_|_$/g, "");
  return `${safe(fullName)}_${safe(company)}_${safe(title)}_ATS`.slice(0, 100);
}
