-- AlterTable
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "tailoredLatex" TEXT;
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "atsExplanation" TEXT;
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "resumeGuardLog" TEXT NOT NULL DEFAULT '[]';
